services:
  fastapi_madr_db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10  

  fastapi_madr_img:
    image: fastapi_madr_img
    entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - fastapi_madr_db
    env_file:
      - .env  
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@fastapi_madr_db:5432/app_db

volumes:
  pgdata: